name: Lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  ktlint:
    name: Run KtLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install KtLint
        run: |
          curl -sS https://github.com/pinterest/ktlint/releases/download/0.50.0/ktlint && chmod +x ktlint && sudo mv ktlint /usr/local/bin/ktlint

      - name: Run KtLint check
        run: ktlint --android --format

      - name: Upload KtLint report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ktlint-report
          path: build/reports/ktlint/ktlintCheck.txt
