name: Lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  ktlint:
    name: Run KtLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 (Adoptium)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Add permissions to Gradle
        run: chmod +x gradlew

      - name: Create local.properties file
        run: echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties

      - name: Install KtLint
        run: |
          curl -sSLo ktlint https://github.com/pinterest/ktlint/releases/download/0.50.0/ktlint
          if [ ! -f ktlint ]; then echo "KtLint download failed"; exit 1; fi
          chmod +x ktlint
          sudo mv ktlint /usr/local/bin/ktlint

      - name: Run Ktlint check with autofix
        run: ./gradlew ktlintCheck